apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: k8s.gcr.io/kube-controller-manager:v1.30.0
    command:
    - kube-controller-manager
    - --kubeconfig=/etc/kubernetes/kubeconfig 
    - --leader-elect=false 
    - --cloud-provider=external 
    - --service-cluster-ip-range=10.0.0.0/24 
    - --cluster-name=kubernetes 
    - --root-ca-file=/etc/kubernetes/ca.crt 
    - --service-account-private-key-file=/tmp/sa.key 
    - --use-service-account-credentials=true 
    - --v=2 
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: kubeconfig
      mountPath: /etc/kubernetes
  volumes:
  - name: tmp
    hostPath:
      path: /tmp
  - name: kubeconfig
    hostPath:
      path: /var/lib/kubelet
